units:
  kx: u
  ky: u
  px: kx + 2
  py: ky + 2
  
  w: 18
  h: 17

  $default_width: u
  $default_height: u

  starting_x: 100
  starting_y: -120

  # Default M2 Screws
  screwSize: 1
  standoffSize: 2.5

points:
  zones:
    matrix:
      anchor:
        shift: [starting_x, starting_y]
      columns:
        1:
        2:
          rows.r0.skip: true
          rows.r0:
            key:
            height: 2u
            # shift: [0, -.5u]
            tags: vert2u
        3:
        4:
          rows.r0.skip: true
          rows.r2.skip: true
      rows:
        r0:
        r1:
        r2:
        r3:

      # this is a test