meta:
  engine: 4.1.0
units:
  kx: u
  ky: u
  px: kx + 2
  py: ky + 2
  w: 18
  h: 17
  $default_width: u
  $default_height: u
  starting_x: 100
  starting_y: -120
  # Default M2 Screws
  screwSize: 1
  standoffSize: 2.5

points:
  zones:
    matrix:
      anchor:
        shift: [starting_x, starting_y]
      columns:
        1:
          rows:
            r0:
              width: 2u
              adjust:
                shift: [0.5u, 0]
              tags: horiz2u
              column_net: P3
            r1:
              column_net: P2
            r2:
              column_net: P0
            r3:
              column_net: P1
        2:
          rows:
            r0:
              skip: true
            r1:
              column_net: P6
            r2:
              column_net: P5
            r3:
              column_net: P4
        3:
          rows:
            r0:
              column_net: P8
            r1:
              column_net: P7
            r2:
              column_net: P6
            r3:
              column_net: P19
        4:
          rows:
            r0:
              skip: true
            r1:
              key:
                height: 2u
                shift: [0, -.5u]
              tags: vert2u
              column_net: P20
            r2:
              skip: true
            r3:
              key:
                height: 2u
              tags: vert2u
              column_net: P21
      rows:
        r0:
        r1:
        r2:
        r3:

outlines:
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5, ky-0.5]
  keycaps:
    - what: rectangle
      where: true
      size: [kx-0.5, ky-0.5]
    - what: rectangle
      where: [vert2u]
      size: [(kx*1)-0.5, (2ky)-0.5]
    - what: rectangle
      where: [horiz2u]
      size: [(kx*2)-0.5, (1ky)-0.5]
      fillet: 1
  outline:
    - what: polygon
      operation: stack
      fillet: 1
      points:
        - ref: matrix_1_r3
          shift: [-0.5px, 0.5py]
        - ref: matrix_1_r3
          shift: [3.2px, 0.5py]
        - ref: matrix_1_r3
          shift: [3.2px, -3.2py]
        - ref: matrix_1_r3
          shift: [-0.5px, -3.2py]
  combo:
    - name: outline
    - operation: stack
      name: keycaps

pcbs:
  numpad-wireless:
    template: kicad8
    outlines:
      main:
        outline: outline
    footprints:
      mx_hotswap:
        what: ceoloide/switch_mx
        where: true
        params:
          hotswap: true
          from: "{{column_net}}"
          to: GND
        adjust:
          rotate: -90
      nicenano:
        what: ceoloide/mcu_nice_nano
        where: matrix_1_r3 # estimate... real one is in pcb
        adjust:
          shift: [0.1kx, -0.3ky]
        params:
          reverse_mount: true
          side: B
      battery_connector:
        what: ceoloide/battery_connector_jst_ph_2
        where: matrix_1_r3
        adjust:
          shift: [-0.1kx, -2.5ky]
          rotate: 90
        params:
          side: B
      on_off_switch:
        what: ceoloide/power_switch_smd_side
        where: matrix_1_r3
        adjust:
          shift: [0.7kx, 0.47ky]
          rotate: 90
        params:
          from: BAT_P
      reset_switch:
        what: ceoloide/reset_switch_smd_side
        params:
          from: GND
          to: RST
        where: matrix_1_r3
        adjust:
          shift: [1.5kx, 0.47ky]
      routes_fp_542:
        what: router
        where: matrix_1_r3
        params:
          locked: false
          routes:
            - "B(0.64,-12.785)(-7.535,-12.785)(-7.62,-12.7)" # net: P1
            - "B(0.64,6.215)(-5.975,-0.4)(-5.975,-9.775)(-6.36,-10.16)(-7.62,-10.16)" # net: P0
            - "B(57.64,34.715)(51.55,28.625)(51.55,-3.025)(39.815,-14.76)(16.86931,-14.76)(16.635,-14.52568)(16.50931,-14.4)(13.325,-11.21569)(13.325,-5.705)(7.62,0)" # net: P20
            - "B(38.64,25.215)(36.665,23.24)(17.39431,23.24)(16.21931,24.415)(4.66206,24.415)(2.68706,22.44)(-1.32226,22.44)(-6.07,17.69226)(-6.07,11.71)(-7.62,10.16)" # net: P7
            - "B(19.64,25.215)(4.33069,25.215)(2.35569,23.24)(-1.65363,23.24)(-7.625,17.26863)(-7.625,15.245)(-7.62,15.24)" # net: P9
            - "B(38.64,6.215)(36.26652,6.215)(32.15,10.33152)(32.15,21.35)(30.66,22.84)(17.22863,22.84)(16.05363,24.015)(4.82774,24.015)(2.85274,22.04)(-1.15657,22.04)(-5.67,17.52657)(-5.67,9.57)(-7.62,7.62)" # net: P6
            - "B(10.14,44.215)(10.14,31.59)(2.19,23.64)(-1.81931,23.64)(-8.77,16.68931)(-8.77,1.15)(-7.62,0)" # net: P3
            - "B(38.64,-12.785)(37.065,-14.36)(17.035,-14.36)(13.725,-11.05)(13.725,-3.565)(7.62,2.54)" # net: P19
            - "B(19.64,6.215)(17.26652,6.215)(14.525,8.95652)(14.525,23)(13.91,23.615)(4.99343,23.615)(3.01843,21.64)(-0.99088,21.64)(-5.27,17.36088)(-5.27,7.43)(-7.62,5.08)" # net: P5
            - "B(7.62,-2.54)(12.925,-7.845)(12.925,-11.38137)(16.70363,-15.16)(39.98068,-15.16)(51.85568,-3.285)(57.64,-3.285)" # net: P21
            - "B(-7.62,12.7)(-6.47,13.85)(-6.47,17.85794)(-1.48794,22.84)(2.52137,22.84)(4.49637,24.815)(16.385,24.815)(17.56,23.64)(23.065,23.64)(26.025,26.6)(26.025,29.14348)(35.56152,38.68)(35.58,38.68)(38.64,41.74)(38.64,44.215)" # net: P8
            - "B(-7.62,2.54)(-4.87,5.29)(-4.87,13.95)(-1.74,17.08)(-1.36152,17.08)(-0.6,17.84152)(-0.6,19.1852)(-1.74,20.3252)(-0.8252,21.24)(3.18412,21.24)(5.15912,23.215)(13.74431,23.215)(14.125,22.83431)(14.125,11.8)(14.125,-9.64348)(17.26652,-12.785)(19.64,-12.785)" # net: P4
            - "B(-7.62,-2.54)(-9.17,-0.99)(-9.17,16.855)(-0.81,25.215)(0.64,25.215)" # net: P2
        adjust:
          shift: [1.8, -5.8]